# Generated by Django 5.1.4 on 2026-09-03 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="promotions.coupon",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="discount_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
